[package]
name = "ldraw-olr"
version.workspace = true
authors = ["Park Joon-Kyu <segfault87@gmail.com>"]
edition = "2024"

[dependencies]
cgmath.workspace = true
futures-intrusive = "0.4"
image.workspace = true
ldraw = { path = "../ldraw" }
ldraw-ir = { path = "../ir" }
ldraw-renderer = { path = "../renderer" }
serde.workspace = true
uuid.workspace = true
wgpu.workspace = true
